import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { db, auth } from "../firebase-config";
import { collection, getDocs, query, orderBy } from "firebase/firestore";
import { useAuthState } from "react-firebase-hooks/auth";
import { signOut } from "firebase/auth";

function ProviderDashboard() {
  const [records, setRecords] = useState([]);
  const [userNames, setUserNames] = useState([]);
  const usersCollectionRef = collection(db, "data");

  // used for confirming the authorization to see the data
  const [user, loading, error] = useAuthState(auth);

  // useState patientName in order to pass props to ProviderDashboard and PatientData pages
  const [patientName, setPatientName] = useState("");

  // this query orders the data on the page by newest date first
  let querySorted = query(usersCollectionRef, orderBy("date", "desc"));

  // function to create list of unique names in db
  function populateNames(records) {
    // create buffer array to be populated with names that are in the database
    let names = [];
    // create variable to track duplicates
    let match = false;
    // loop through all items in records
    for (let item of records) {
      // check names buffer array, set match = true if name is already on the list
      for (let entry of names) {
        if (item.name == entry) {
          match = true;
        }
      }
      if (match == false) {
        // add name to buffer array if it's not on there already
        names.push(item.name);
      }
      // reset match at end of cycle
      match = false;
    }
    // sort names array alphabetically and adds a default entry for the dropdown box
    names.sort().unshift("...   ");
    // update state with buffer array
    setUserNames(names);
  }

  // This area is to read all of the entries on the DB
  // loads data when page is loaded
  useEffect(() => {
    const getEntries = async () => {
      const data = await getDocs(querySorted);
      const dataParsed = data.docs.map((doc) => ({
        ...doc.data(),
        id: doc.id,
      }));
      // puts the retrieved info into the records variable
      setRecords(dataParsed);
      // this is called to get the name list for the dropdown list
      populateNames(dataParsed);
    };
    getEntries();
  }, []);

  // converts the date in the database from seconds to a formatted date
  function dateConvert(input) {
    let formattedDate = new Date(input);
    let month = formattedDate.getMonth();
    let day = formattedDate.getDate();
    let year = formattedDate.getFullYear();
    let dateString = year + "-" + (month + 1) + "-" + day;
    return dateString;
  }

  // logs out the current user and sends them to the Provider login page
  function logout() {
    signOut(auth);
    window.location = "/provider";
  }

  return (
    <div className="dashboard-page">
      {/* checking for existence of displayName, if so indicate that that user is logged in, otherwise indicate email of logged in user */}
      {user ? (
        <div className="login-hud">
          <p>
            <span className="bold">
              Logged in{" "}
              {user.displayName ? `as ${user.displayName}` : `as ${user.email}`}
            </span>
          </p>
          <button onClick={logout}>Sign Out</button>
        </div>
      ) : null}

      <h2 className="login-header">Provider Dashboard</h2>

      <div id="dashboard-header">
        <p className="patient-name bold">All Patients</p>

        <form id="dropdown-form">
          {/* this form is for the dropdown menu to select a patient to view their page */}
          <div id="dropdown-menu">
            <p id="select-tag">Select a patient:</p>
            <select
              type="text"
              onChange={(evt) => {
                setPatientName(evt.target.value);
              }}
            >
              {/* userNames is a list of unique Names in the database generated by populateNames function */}
              {/* adds each entry for the dropdown list */}
              {userNames.map((element) => (
                <option value={element}>{element}</option>
              ))}
            </select>
            <Link
              to="/provider/dashboard/patient-data"
              state={{ patientName: patientName }}
            >
              <button id="dropdown-button" type="submit">
                Select
              </button>
            </Link>
          </div>
        </form>
      </div>

      <div className="dashboard-table">
        <table>
          <thead>
            {/* Heading for the table of entries starts here */}
            <tr>
              <th>Date</th>
              <th>Name</th>
              <th>Bristol Type</th>
              <th>Blood Present?</th>
              <th>Pain Level</th>
            </tr>
          </thead>

          <tbody>
            {/* each entry is returned as a row to this table  */}
            {records.map((entry) => {
              return (
                <tr>
                  {/* the date is formatted for display */}
                  <td>{dateConvert(entry.date)}</td>
                  <td>
                    {/* names are made a link to a page generated from their data */}
                    <Link
                      to="/provider/dashboard/patient-data"
                      state={{ patientName: entry.name }}
                    >
                      {entry.name}
                    </Link>
                  </td>
                  <td>
                    {/* nested ternary for displaying the bristol data for the entry */}
                    {entry.bristol === 0 ? (
                      <span id="bristol0">{entry.bristol}</span>
                    ) : entry.bristol === 1 ? (
                      <span id="bristol1">{entry.bristol}</span>
                    ) : entry.bristol === 2 ? (
                      <span id="bristol2">{entry.bristol}</span>
                    ) : entry.bristol === 3 ? (
                      <span id="bristol3">{entry.bristol}</span>
                    ) : entry.bristol === 4 ? (
                      <span id="bristol4">{entry.bristol}</span>
                    ) : entry.bristol === 5 ? (
                      <span id="bristol5">{entry.bristol}</span>
                    ) : entry.bristol === 6 ? (
                      <span id="bristol6">{entry.bristol}</span>
                    ) : entry.bristol === 7 ? (
                      <span id="bristol7">{entry.bristol}</span>
                    ) : (
                      <span id="bristol-empty">{entry.bristol}</span>
                    )}
                  </td>
                  <td>
                    {/* if there is blook present, this will be displayed red */}
                    {entry.blood ? <span id="blood">YES</span> : "none"}
                  </td>
                  <td>
                    {/* nested ternary for the display of the pain data */}
                    {entry.pain === 0 ? (
                      <span id="pain0">{entry.pain}</span>
                    ) : entry.pain === 1 ? (
                      <span id="pain1">{entry.pain}</span>
                    ) : entry.pain === 2 ? (
                      <span id="pain2">{entry.pain}</span>
                    ) : entry.pain === 3 ? (
                      <span id="pain3">{entry.pain}</span>
                    ) : entry.pain === 4 ? (
                      <span id="pain4">{entry.pain}</span>
                    ) : entry.pain === 5 ? (
                      <span id="pain5">{entry.pain}</span>
                    ) : entry.pain === 6 ? (
                      <span id="pain6">{entry.pain}</span>
                    ) : entry.pain === 7 ? (
                      <span id="pain7">{entry.pain}</span>
                    ) : entry.pain === 8 ? (
                      <span id="pain8">{entry.pain}</span>
                    ) : entry.pain === 9 ? (
                      <span id="pain9">{entry.pain}</span>
                    ) : entry.pain === 10 ? (
                      <span id="pain10">{entry.pain}</span>
                    ) : (
                      <span id="pain-empty">{entry.pain}</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default ProviderDashboard;
